"""Is this model running on THIS machine, or on someone else's?

WHY THIS FILE EXISTS AT ALL.

Arthur's entire premise is that inference is local. That assumption is not just
marketing -- it is wired into the app in ways that become lies if it stops being
true:

  * every message is persisted with `provider = "local"`;
  * the chat UI shows a `cloud · <provider>` badge ONLY for BYOK replies, so no
    badge reads as "this stayed on your machine";
  * the BYOK router exists precisely so that using a remote model is a
    deliberate, configured act;
  * the research composer footer says, in so many words, "Nothing leaves this
    computer."

Ollama now serves models that run on ITS infrastructure, tagged `:cloud`
(`kimi-k3:cloud`, `gemma4:31b-cloud`). To Arthur they look exactly like any
other Ollama model: same client, same API, same code path. Install one and every
prompt, every extracted PDF, and every file Code mode reads is sent to a third
party while the UI insists nothing left the machine.

That is a trust bug, not a feature gap. It bypasses the consent boundary
through the front door.

THE POLICY IMPLEMENTED HERE: cloud models are allowed, never silently. They are
detected, labelled everywhere a model is shown, attributed to the right provider
on stored messages, and excluded from claims about locality. Blocking them
outright was the alternative; it is easier to defend but it would also make a
capable model unusable for someone who has read the label and decided they are
fine with it. Informed choice beats a locked door -- as long as the information
is actually there.
"""

from __future__ import annotations

import re

# Ollama's naming convention for remotely-hosted models. Both shapes appear in
# its library: a bare `:cloud` tag and a size-qualified `-cloud` suffix.
#
# Matching on the NAME is not ideal -- names are strings and strings lie -- but
# it is the only signal available before a model is installed, which is exactly
# when the user most needs to be told. `capabilities()` cannot help: it requires
# a local `show`, and by then the decision has been made.
_CLOUD_RE = re.compile(r"(?::cloud$|-cloud(?::|$))", re.I)

# What to call the provider on a stored message. Deliberately NOT "local", and
# deliberately distinct from the BYOK provider names ("anthropic", "openai"),
# so a transcript makes clear which third party actually saw the conversation.
CLOUD_PROVIDER = "ollama-cloud"


def is_cloud_model(name: str) -> bool:
    """True when this tag runs on Ollama's servers rather than this machine."""
    return bool(_CLOUD_RE.search((name or "").strip()))


def provider_for(name: str) -> str:
    """The `provider` to record against a message generated by this model."""
    return CLOUD_PROVIDER if is_cloud_model(name) else "local"


def locality_note(name: str) -> str:
    """One sentence about where the work happens, for UI that promises privacy.

    The local string is the claim Arthur has always made. The cloud string
    exists so that claim is never printed next to a model that would falsify
    it -- a privacy promise that is sometimes false is worse than none, because
    it is the one people stop checking.
    """
    if is_cloud_model(name):
        return "This model runs on Ollama's servers, so your question and any attached files leave this computer."
    return "Nothing leaves this computer."
